fix: celery flower auth optional

diff --git a/trade_portal/compose/production/django/celery/flower/start b/trade_portal/compose/production/django/celery/flower/start
--- a/trade_portal/compose/production/django/celery/flower/start
+++ b/trade_portal/compose/production/django/celery/flower/start
@@ -1,14 +1,28 @@
-#!/bin/bash
+#!/bin/sh
 
 set -o errexit
 set -o nounset
 
-if [ -n "${CELERY_FLOWER_PASSWORD_ENCRYPTED}" ]; then
-    echo ${CELERY_FLOWER_PASSWORD#"${KMS_PREFIX}"}| base64 -d > "/tmp/cipher.blob"
-    CELERY_FLOWER_PASSWORD="$(aws --region "${AWS_REGION}" kms decrypt --ciphertext-blob "fileb:///tmp/cipher.blob" --output text --query Plaintext | base64 -d || return $?)"
+CELERY_FLOWER_USER="${CELERY_FLOWER_USER:-""}"
+CELERY_FLOWER_PASSWORD="${CELERY_FLOWER_PASSWORD:-""}"
+CELERY_FLOWER_PASSWORD_ENCRYPTED="${CELERY_FLOWER_PASSWORD_ENCRYPTED:-"false"}"
+
+KMS_PREFIX="${KMS_PREFIX:-"kms+base64:"}"
+
+if [[ -n "${CELERY_FLOWER_USER}" && -n "${CELERY_FLOWER_PASSWORD}" ]]; then
+    if [[ "${CELERY_FLOWER_PASSWORD_ENCRYPTED}" == "true" ]]; then
+        echo "${CELERY_FLOWER_PASSWORD#${KMS_PREFIX}}" | base64 -d > "/tmp/cipher.blob"
+        CELERY_FLOWER_PASSWORD="$(aws --region "${AWS_REGION}" kms decrypt --ciphertext-blob "fileb:///tmp/cipher.blob" --output text --query Plaintext | base64 -d )"
+
+        if [[ -z "${CELERY_FLOWER_PASSWORD}" ]]; then
+            echo "Celery Password was supposed to be encrypted but we couldn't decrypt it"
+            exit 255
+        fi
+    fi
+
+    export FLOWER_BASIC_AUTH="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
 fi
 
 celery flower \
-    --app=config.celery_app \
-    --broker="${CELERY_BROKER_URL}" \
-    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
+    --app=chambers_app.taskapp \
+    --broker="${CELERY_BROKER_URL}"
